Fix wget on AIX not retrying
It was return zero even on failure!

diff --git a/deps-packaging/pkg-get-src b/deps-packaging/pkg-get-src
--- a/deps-packaging/pkg-get-src
+++ b/deps-packaging/pkg-get-src
@@ -87,6 +87,7 @@ fetch_file()
     FILENAME="$1"
     CHECKSUM="$2"
 
+    OUTFILE="$CACHEDIR/$FILENAME"
     WGET=`func_whereis wget`
 
     mkdir -p "$CACHEDIR"
@@ -97,19 +98,21 @@ fetch_file()
         # Also, the standard output of this function is parsed, so let's make sure
         # wget outputs on standard error. That's what it normally does anyway, but
         # misparsed arguments is an exception.
-        $WGET --no-check-certificate -t5 "$URL$FILENAME" -O "$CACHEDIR/$FILENAME" 1>&2 \
-            || $WGET -t5 "$URL$FILENAME" -O "$CACHEDIR/$FILENAME" 1>&2  \
-            || true
+        $WGET --no-check-certificate -t5 "$URL$FILENAME" -O "$OUTFILE" 1>&2  ||  true
 
-        if [ -f "$CACHEDIR/$FILENAME" ]
+        # Some wget (1.9.1 on AIX) return 0 even when they failed! So we
+        # must test for file existence for retrying.
+        [ -f "$OUTFILE" ]  ||  $WGET -t5 "$URL$FILENAME" -O "$OUTFILE" 1>&2  ||  true
+
+        if [ -f "$OUTFILE" ]
         then
-            if checksum "$CACHEDIR/$FILENAME" "$CHECKSUM"
+            if checksum "$OUTFILE" "$CHECKSUM"
             then
                 return 0                           # SUCCESSFUL DOWNLOAD
             else
                 info "WARNING: Downloaded $URL$FILENAME has wrong checksum. Continuing"
                 # wget(1) tends to create empty files even if download did not finish
-                rm -f "$CACHEDIR/$FILENAME"
+                rm -f "$OUTFILE"
             fi
         fi
     done
