port of auto build 2.2.x branch to build 2.2.x packages.

diff --git a/build-remote b/build-remote
--- a/build-remote
+++ b/build-remote
@@ -2,8 +2,6 @@
 
 set -e
 
-. `dirname "$0"`/build-scripts/functions
-
 usage() {
   echo
   echo "Usage: build-remote [--wix-machine=<user@host>]"
@@ -11,17 +9,11 @@ usage() {
   echo "                    [--project=<project>]"
   echo "                    [--branch=<branch>]"
   echo "                    [--source=<url>]"
-  echo "                    [--role=<hub|agent>]"
-  echo "                    [--version=<version string>]"
-  echo "                    [--test-machine=chroot]"
-  echo "                    [--workdir=/opt/cfengine]"
-  echo "                    [--full|--release|--debug|--docs|--release-and-debug]"
-  echo "                    [-v|--verbose]"
+  echo "                    [--full|--release|--debug|--docs]"
   echo "                    <user@host>"
   echo
   echo "Project defaults to 'nova'"
-  echo "Branch defaults to 'master', specify --branch=cp if you just want to do simple rsync from the source directories"
-  echo "workdir defaults to '/var/cfengine'"
+  echo "Branch defaults to 'master'"
   echo "Build type defaults to quick. You may request a full build using --full"
   echo "Source defaults to git@github.com:cfengine/"
   echo
@@ -30,10 +22,9 @@ usage() {
 }
 
 opts() {
-  OPTS=`getopt -o p:b:w:c:d:vht: --long project:,branch:,wix-machine:,cross-target:,workdir:,verbose,source:,role:,version:,full,release,debug,docs,release-and-debug,help,test-machine: -n build-remote -- "$@"`
+  OPTS=`getopt -o p:b:w:c:h --long project:,branch:,wix-machine:,cross-target:,source:,full,release,debug,docs,help -n build-remote -- "$@"`
 
   eval set -- "$OPTS"
-  echo "$?"
 
   if [ $? != 0 ]; then
     usage
@@ -45,9 +36,7 @@ opts() {
   BRANCH=master
   BUILD_TYPE=quick
   SOURCE=git@github.com:cfengine
-  BUILD_NUMBER=${BUILD_NUMBER:-666}
-  EXPLICIT_ROLE=
-  TEST_MACHINE=${TEST_MACHINE:-}
+  BUILD_NUMBER=666
 
   while true; do
     case "$1" in
@@ -63,12 +52,6 @@ opts() {
       -c|--cross-target)
         CROSS_TARGET="$2"
         shift 2;;
-      -d|--workdir)
-        PREFIX="$2"
-        shift 2;;
-      -v|--verbose)
-        VERBOSE=yes
-        shift;;
       --full)
         BUILD_TYPE=full
         shift;;
@@ -78,35 +61,15 @@ opts() {
       --debug)
         BUILD_TYPE=debug
         shift;;
-	  --release-and-debug)
-	    BUILD_TYPE=debug_and_release
-		shift;;
       --docs)
         DOCS=yes
         shift;;
       --source)
         SOURCE="$2"
         shift 2;;
-      --role)
-	    EXPLICIT_ROLE="$2"
-		shift 2;;
-	  --version)
-	    EXPLICIT_VERSION="$2"
-		shift 2;;
       -h|--help)
         usage
         exit 0;;
-      -t|--test-machine)
-        TEST_MACHINE="$2"
-        case "$TEST_MACHINE" in
-          chroot)
-            ;;
-          *)
-            echo "Only --test-machine=chroot is supported"
-            exit 1
-            ;;
-        esac
-        shift 2;;
       --)
         shift
         break;;
@@ -115,16 +78,16 @@ opts() {
         exit 1;;
     esac
   done
-  echo "$PROJECT $BRANCH $HOST $BUILD_TYPE $SOURCE"
+
   if [ $# -ne 1 ]; then
     usage
     exit 1
   fi
-
+  
   REPOSITORY=$PROJECT-$BRANCH
   HOST=$1
 
-  export PROJECT BRANCH WIX_MACHINE CROSS_TARGET HOST BUILD_TYPE BUILD_NUMBER DOCS EXPLICIT_ROLE EXPLICIT_VERSION TEST_MACHINE PREFIX
+  export PROJECT BRANCH WIX_MACHINE CROSS_TARGET HOST BUILD_TYPE BUILD_NUMBER DOCS
 
   export SCHEDULER=$PROJECT-$BRANCH-localbuild
 }
@@ -132,50 +95,40 @@ opts() {
 prepare_workdir() {
   mkdir -p "workdir-$PROJECT-$BRANCH-$HOST"
   rm -rf "workdir-$PROJECT-$BRANCH-$HOST"/*
-  # In order for tail not to miss any output. If it doesn't exist, there is a small window between
-  # when it is created and when tail discovers it, where output may be missed.
-  touch "workdir-$PROJECT-$BRANCH-$HOST"/build-remote.log
-
-  SCRIPT="$(readlink -f "$0")"
-  AUTOBUILD_PATH="$(pwd)/workdir-$PROJECT-$BRANCH-$HOST/build/autobuild"
-  export AUTOBUILD_PATH
   cd "workdir-$PROJECT-$BRANCH-$HOST"
-
-  checkout
 }
 
 checkout() {
   mkdir -p build
-  rsync -avr --exclude='workdir-*' --exclude=".git" ../ build/autobuild
-  #(cd build/autobuild && git add -A || :; git commit -a -m "Commit for build" || :)
-
-  REPOS="core masterfiles"
-
-  case "$PROJECT" in
-     nova)
-      REPOS="$REPOS nova design-center mission-portal"
-  esac
+  rsync -avr --exclude='workdir-*' ../ build/autobuild
+  (cd build/autobuild && git add -A || :; git commit -a -m "Commit for build" || :)
 
   case "$PROJECT-$BRANCH" in
     community-master)
       git clone $SOURCE/core build/core
-      git clone $SOURCE/masterfiles build/masterfiles
-      (cd build/masterfiles && git checkout $VERSION) || false
-      git clone $SOURCE/design-center build/design-center
-      (cd build/design-center && git checkout $VERSION) || false
       ;;
-    community-3.4.x)
-      git clone $SOURCE/core build/core
-      (cd build/core && git checkout 3.4.x) || false
-     ;;
     community-3.3.x)
       git clone $SOURCE/core build/core
       (cd build/core && git checkout -b 3.3.x remotes/origin/3.3.x || git checkout 3.3.x) || false
       ;;
-    community-3.4.*)
+    community-3.3.*)
       VERSION=$BRANCH
       git clone $SOURCE/core build/core
       (cd build/core && git checkout $VERSION) || false
+      ;;
+    nova-2.2.x)
+      VERSION=$BRANCH
+      git clone $SOURCE/nova build/nova
+      (cd build/nova && git checkout $VERSION) || false
+      git clone $SOURCE/core build/core
+      (cd build/core && git checkout 3.3.x) || false
+      ;;
+    nova-2.2.9)
+      VERSION=$BRANCH
+      git clone $SOURCE/nova build/nova
+      (cd build/nova && git checkout $VERSION) || false
+      git clone $SOURCE/core build/core
+      (cd build/core && git checkout 3.3.19) || false
       ;;
     nova-2.2.2)
       VERSION=$BRANCH
@@ -184,17 +137,21 @@ checkout() {
       git clone $SOURCE/core build/core
       (cd build/core && git checkout 3.3.6) || false
       ;;
-    nova-3.5.x)
+    nova-2.2.6i)
       VERSION=$BRANCH
       git clone $SOURCE/nova build/nova
       (cd build/nova && git checkout $VERSION) || false
       git clone $SOURCE/core build/core
-      (cd build/core && git checkout $VERSION) || false
-      git clone $SOURCE/mission-portal build/mission-portal
-      git clone $SOURCE/design-center build/design-center
-      (cd build/design-center && git checkout $VERSION)
+      (cd build/core && git checkout 3.3.15i) || false
       ;;
-    nova-2.2.*)
+    nova-2.2.6f)
+      VERSION=$BRANCH
+      git clone $SOURCE/nova build/nova
+      (cd build/nova && git checkout $VERSION) || false
+      git clone $SOURCE/core build/core
+      (cd build/core && git checkout 3.3.15f) || false
+      ;;
+    nova-2.2.7)
       VERSION=$BRANCH
       git clone $SOURCE/nova build/nova
       (cd build/nova && git checkout $VERSION) || false
@@ -203,50 +160,57 @@ checkout() {
       ;;
     nova-master)
       git clone $SOURCE/core build/core
-      git clone $SOURCE/enterprise build/enterprise
       git clone $SOURCE/nova build/nova
-      git clone $SOURCE/mission-portal build/mission-portal
-      git clone $SOURCE/design-center build/design-center
-      git clone $SOURCE/masterfiles build/masterfiles
       ;;
-    nova-3.6.x)
-      VERSION=$BRANCH
-      git clone $SOURCE/core build/core
-       (cd build/core && git checkout $VERSION) || false
-      git clone $SOURCE/nova build/nova
-      (cd build/nova && git checkout $VERSION) || false
-      git clone $SOURCE/enterprise build/enterprise
-       (cd build/enterprise && git checkout $VERSION) || false
-      git clone $SOURCE/mission-portal build/mission-portal
-       (cd build/mission-portal && git checkout $VERSION) || false
-      git clone $SOURCE/design-center build/design-center
-       (cd build/design-center && git checkout $VERSION) || false
-      git clone $SOURCE/masterfiles build/masterfiles
-       (cd build/masterfiles && git checkout $VERSION)
-       ;;
-      
-    nova-cp)
-     rsync -avr --exclude='workdir-*' $AUTOBUILD_PATH/ build/autobuild
-     for d in core nova enterprise masterfiles design-center mission-portal; do
-       rsync -avr $SOURCE/$d build
-     done
-      ;;
-
     nova-stable)
       git clone $SOURCE/core build/core
-      (cd build/core && git checkout -b 3.4.x remotes/origin/3.4.x || git checkout 3.4.1n) || false
+      (cd build/core && git checkout stable) || false
       git clone $SOURCE/nova build/nova
-      (cd build/nova && git checkout -b 3.0.x remotes/origin/3.0.x || git checkout 3.0.0) || false
+      (cd build/nova && git checkout stable) || false
       git clone $SOURCE/mission-portal build/mission-portal
-      (cd build/mission-portal && git checkout -b 3.0.x remotes/origin/3.0.x || git checkout 3.0.0) || false
+      (cd build/mission-portal && git checkout stable) || false
       ;;
     *)
-      for i in $REPOS;
-         do
-         git clone $SOURCE/$i build/$i
-         (cd build/$i && git checkout -b $BRANCH remotes/origin/$BRANCH || git checkout $BRANCH) || false
-      done
+      echo "WAT?"
+      exit 42;;
   esac
+}
+
+run() {
+  NAME="$1"
+  shift
+  echo "---> $NAME"
+  if ! "$@" > "$NAME.log" 2>&1; then
+    echo "Failed. See the $NAME.log. Last lines are:"
+    tail $NAME.log
+    exit 1
+  fi
+}
+
+local_script() {
+  SCRIPT="$1"
+  run "$SCRIPT" "build/autobuild/build-scripts/$SCRIPT" "$HOST"
+}
+
+remote_script() {
+  SCRIPT="$1"
+  ENVVARS="PROJECT=$PROJECT"
+  if [ -n "$CROSS_TARGET" ]; then
+    ENVVARS="$ENVVARS CROSS_TARGET=$CROSS_TARGET"
+  fi
+  if [ -n "$WIX_MACHINE" ]; then
+    ENVVARS="$ENVVARS WIX_MACHINE=$WIX_MACHINE"
+  fi
+  if [ -n "$BUILD_TYPE" ]; then
+    ENVVARS="$ENVVARS BUILD_TYPE=$BUILD_TYPE"
+  fi
+  if [ -n "$BUILD_NUMBER" ]; then
+    ENVVARS="$ENVVARS BUILD_NUMBER=$BUILD_NUMBER"
+  fi
+
+  ENVVARS="$ENVVARS BRANCH=$REPOSITORY"
+
+  run "$SCRIPT" ssh -o BatchMode=yes "$HOST" env $ENVVARS build/autobuild/build-scripts/"$SCRIPT"
 }
 
 build_docs() {
@@ -258,12 +222,6 @@ build_docs() {
 build() {
   remote_script configure
   remote_script compile
-  case "$BUILD_TYPE" in
-    debug_and_release)
-	  remote_script produce-debug-symbols
-	  ;;
-  esac
-
   remote_script test
   remote_script package
   remote_script prepare-results
@@ -274,13 +232,10 @@ build() {
 }
 
 common_build() {
-  if [ "$VERBOSE" = "yes" ]; then
-    tail -F --pid=$$ build-remote.log &
-  fi
 
+  checkout
   local_script autogen
   local_script transfer-to-buildmachine
-  remote_script build-environment-check
   remote_script clean-buildmachine
   remote_script install-dependencies
 
diff --git a/packaging/cfengine-nova/cfengine-nova.spec.in b/packaging/cfengine-nova/cfengine-nova.spec.in
--- a/packaging/cfengine-nova/cfengine-nova.spec.in
+++ b/packaging/cfengine-nova/cfengine-nova.spec.in
@@ -1,4 +1,4 @@
-%define prefix %{buildprefix}
+%define prefix /var/cfengine
 
 Summary: The CFEngine Configuration System
 Name: cfengine-nova
@@ -9,13 +9,24 @@ License: COSL
 Group: Applications/System
 URL: http://cfengine.com/
 BuildRoot: %{_topdir}/%{name}-%{version}-%{release}-buildroot
-Obsoletes: cfengine3, cfengine-community, cfengine-nova
-Requires: coreutils gzip
+Obsoletes: cfengine3, cfengine-community
 
 AutoReqProv: no
 
 %if %{?with_debugsym}%{!?with_debugsym:0}
 %define debug_package {nil}
+%endif
+
+%if %{?with_expansion}%{!?with_expansion:0}
+Source0: cfconvert
+%endif
+
+%if %{?with_expansion}%{!?with_expansion:0}
+%package expansion
+Summary: The CFEngine Configuration System -- web-interface
+Group: Applications/System
+Requires: cfengine-nova = %{version}-%{release}
+AutoReqProv: no
 %endif
 
 %description
@@ -24,27 +35,74 @@ leading enterprises since 1993. Customize your IT systems, align to network,
 business and regulatory needs, monitor problems, automatically repair and
 maintain systems.
 
+%if %{?with_expansion}%{!?with_expansion:0}
+%description expansion
+CFEngine is the standalone, open-source datacenter management platform run by
+leading enterprises since 1993. Customize your IT systems, align to network,
+business and regulatory needs, monitor problems, automatically repair and
+maintain systems.
+
+This package contains the web-interface for CFEngine Nova.
+%endif
+
 %install
 rm -rf $RPM_BUILD_ROOT
 
 mkdir -p $RPM_BUILD_ROOT%{prefix}
 cp -a %{prefix}/* $RPM_BUILD_ROOT%{prefix}
-cp -a %{_basedir}/cfengine/dist/* $RPM_BUILD_ROOT
-
-#Copy the modified init.d script according to the working directory
-cp %{_basedir}/enterprise/misc/init.d/cfengine3 $RPM_BUILD_ROOT/etc/init.d/cfengine3
-
+cp -a %{_basedir}/core/dist/* $RPM_BUILD_ROOT
 
 # Remove useless stuff
 
 rm -f $RPM_BUILD_ROOT%{prefix}/lib/libpromises.la
 rm -f $RPM_BUILD_ROOT%{prefix}/lib/libpromises.so
-rm -f $RPM_BUILD_ROOT%{prefix}/lib/cfengine-enterprise.la
 rm -rf $RPM_BUILD_ROOT%{prefix}/share/CoreBase
-rm -f $RPM_BUILD_ROOT%{prefix}/bin/getfacl
-rm -f $RPM_BUILD_ROOT%{prefix}/bin/openssl
-rm -rf $RPM_BUILD_ROOT%{prefix}/ssl
 
+%if %{?with_expansion}%{!?with_expansion:0}
+
+rm -f $RPM_BUILD_ROOT%{prefix}/lib/php/cfmod.la
+rm -f $RPM_BUILD_ROOT%{prefix}/lib/php/cfengine-enterprise-api.la
+
+# GUI, REST, KB
+
+cp -R %{_basedir}/nova/GUI2 $RPM_BUILD_ROOT%prefix/share/GUI
+cp -R %{_basedir}/nova/rest $RPM_BUILD_ROOT%prefix/share/rest
+cp -R %{_basedir}/nova/knowledge $RPM_BUILD_ROOT%prefix/share/KnowledgeBase
+cp -R %{_basedir}/nova/misc/solaris_admin_files $RPM_BUILD_ROOT%prefix/share
+rm -rf $RPM_BUILD_ROOT%prefix/share/GUI/tests
+rm -rf $RPM_BUILD_ROOT%prefix/share/GUI/application/controllers/testing.php
+rm -rf $RPM_BUILD_ROOT%prefix/share/GUI/unittest_index.php
+rm -rf $RPM_BUILD_ROOT%prefix/share/GUI/unit_test.php
+rm -rf $RPM_BUILD_ROOT%prefix/share/rest/tests
+
+# Change development mode in MP to production mode
+
+sed "s/define('ENVIRONMENT', 'development')/define('ENVIRONMENT','production')/g" $RPM_BUILD_ROOT%prefix/share/GUI/index.php > $RPM_BUILD_ROOT%prefix/share/GUI/index.php.tmp
+mv $RPM_BUILD_ROOT%prefix/share/GUI/index.php.tmp $RPM_BUILD_ROOT%prefix/share/GUI/index.php
+rm -f $RPM_BUILD_ROOT%prefix/share/GUI/index.php.tmp
+
+# NovaBase
+
+cp -R %{_basedir}/nova/masterfiles $RPM_BUILD_ROOT%prefix/share/NovaBase
+if [ -f %{_basedir}/core/masterfiles/cfengine_stdlib.cf ]; then
+	cp %{_basedir}/core/masterfiles/cfengine_stdlib.cf $RPM_BUILD_ROOT%prefix/share/NovaBase
+else
+	cp -R %{_basedir}/core/masterfiles/libraries $RPM_BUILD_ROOT%prefix/share/NovaBase
+fi
+# cfconvert
+
+cp $RPM_SOURCE_DIR/cfconvert $RPM_BUILD_ROOT%prefix/bin
+
+if [ -f /var/cfengine/include/sqlite3.h ]; then
+	sudo rm -rf /var/cfengine/include
+	sudo rm -f /var/cfengine/lib/libsqlite3.so
+fi
+
+# Cleanup
+
+find $RPM_BUILD_ROOT%prefix -name .svn | xargs -r rm -rf
+
+%endif
 
 %clean
 rm -rf $RPM_BUILD_ROOT
@@ -103,9 +161,6 @@ if [ ! -f %prefix/ppkeys/localhost.priv ]; then
     %prefix/bin/cf-key >/dev/null || :
 fi
 
-if [ -f %prefix/bin/cf-twin ]; then
-    /bin/rm %prefix/bin/cf-twin
-fi
 
 /bin/cp %prefix/bin/cf-agent %prefix/bin/cf-twin
 for i in cf-agent cf-promises cf-key cf-execd cf-serverd cf-monitord cf-runagent;
@@ -171,6 +226,29 @@ done
 
 exit 0
 
+%if %{?with_expansion}%{!?with_expansion:0}
+%post expansion
+
+#
+# Use default policy in case of fresh installation.
+#
+if ! [ -f %prefix/masterfiles/promises.cf ]; then
+ /bin/cp -R %prefix/share/NovaBase/* %prefix/masterfiles
+fi
+exit 0
+
+%preun expansion
+
+if [ -f /usr/bin/killall ]; then
+ /usr/bin/killall -q -15 mongod
+ /bin/rm -f %prefix/state/mongod.lock
+else
+ /usr/bin/pkill -15 mongod || true
+ /bin/rm -f %prefix/state/mongod.lock
+fi
+exit 0
+%endif
+
 %files
 %defattr(755,root,root)
 
@@ -180,38 +258,29 @@ exit 0
 %prefix/bin/cf-agent
 %prefix/bin/cf-execd
 %prefix/bin/cf-key
+%prefix/bin/cf-know
 %prefix/bin/cf-monitord
 %prefix/bin/cf-promises
+%prefix/bin/cf-report
 %prefix/bin/cf-runagent
 %prefix/bin/cf-serverd
-%prefix/bin/cf-upgrade
-
-# LMDB
-%prefix/bin/lmdump
-%prefix/bin/lmmgr
-%prefix/bin/mdb_copy
-%prefix/bin/mdb_stat
-
-# Auxiliary programs
-%if "%{version}" >= "3.0"
-%prefix/bin/rpmvercmp
-%endif
+%prefix/bin/tchmgr
+%dir %prefix/lib
+%prefix/lib/lib*.so.*
 
 # Initscript, other configuration
 /etc/init.d/cfengine3
 /etc/sysconfig/cfengine3
 /etc/profile.d/cfengine.sh
 
-%defattr(644,root,root,755)
-%dir %prefix/lib
-%prefix/lib/lib*.so*
-%prefix/lib/cfengine-enterprise.so
-
 # Documentation
 %dir %prefix/share
+%prefix/share/man
 %prefix/share/doc
 
 # Private directories
+
+%dir %prefix/masterfiles
 
 %defattr(700,root,root)
 %dir %prefix/ppkeys
@@ -219,5 +288,32 @@ exit 0
 %dir %prefix/inputs
 %dir %prefix/modules
 
+%if %{?with_expansion}%{!?with_expansion:0}
+%files expansion
+%defattr(755,root,root)
+
+# Nova-only binaries
+%prefix/bin/cf-hub
+%prefix/bin/cfconvert
+%prefix/bin/mongo*
+
+# PHP modules
+%prefix/lib/php
+
+# Base policy
+%prefix/share/NovaBase
+
+# Web interface
+%prefix/share/GUI
+%prefix/share/rest
+%prefix/share/KnowledgeBase
+
+#Solaris upgrade files
+%prefix/share/solaris_admin_files
+
+# Software upgrade delivery area
+%prefix/master_software_updates
+
+%endif
 
 %changelog
