Redmine #6581: Fix upgrade overwriting config files with templates.
This required several things:

- Almost all of the post script was only executed on install, not
  upgrade. Now most (but not all) sections are performed on both.
- The config files contain the private keys, but we don't have a
  dedicated file for them, so we need to fish them out of the config
  files, store them somewhere, and then restore them after the file
  has been upgraded.
- Lots of indentation corrections.
- Don't regenerate new SSL certificate if we already have one.

diff --git a/packaging/cfengine-nova-hub/debian/cfengine-nova-hub.preinst b/packaging/cfengine-nova-hub/debian/cfengine-nova-hub.preinst
--- a/packaging/cfengine-nova-hub/debian/cfengine-nova-hub.preinst
+++ b/packaging/cfengine-nova-hub/debian/cfengine-nova-hub.preinst
@@ -11,10 +11,10 @@ PREFIX=/var/cfengine
 NAME=$(hostname -f)
 if [ -z "$NAME" ];
 then
-    echo "hostname -f does not return a valid name, this is a configuration problem on this host."
-	echo "Please make sure that hostname -f returns a valid name (Add an entry to /etc/hosts or "
-	echo "fix the name resolution)."
-	exit 1
+  echo "hostname -f does not return a valid name, this is a configuration problem on this host."
+  echo "Please make sure that hostname -f returns a valid name (Add an entry to /etc/hosts or "
+  echo "fix the name resolution)."
+  exit 1
 fi
 
 # 
@@ -26,25 +26,25 @@ fi
 HTTPD_RUNNING=`netstat -natp | grep -E "(:80\s|:443\s).*LISTEN"`
 if [ ! -z "$HTTPD_RUNNING" ];
 then
-	echo "There seems to be a server listening on either port 80 or 443"
-	echo "Checking if it is part of CFEngine Enterprise"
-	if [ -x $PREFIX/httpd/bin/apachectl ];
-	then
-		echo "Trying to shut down the process using apachectl from CFEngine Enterprise"
-		$PREFIX/httpd/bin/apachectl stop
-		HTTPD_RUNNING=`netstat -natp | grep -E "(:80\s|:443\s).*LISTEN"`
-		if [ ! -z "$HTTPD_RUNNING" ];
-		then
-			echo "Could not shutdown the process, aborting the installation"
-			exit 1
-		fi
-	else
-		echo "No apachectl found, aborting the installation!"
-		echo "Please kill the following processes before attempting a new installation"
-		fuser -n tcp 80
-		fuser -n tcp 443
-		exit 1
-	fi
+  echo "There seems to be a server listening on either port 80 or 443"
+  echo "Checking if it is part of CFEngine Enterprise"
+  if [ -x $PREFIX/httpd/bin/apachectl ];
+  then
+    echo "Trying to shut down the process using apachectl from CFEngine Enterprise"
+    $PREFIX/httpd/bin/apachectl stop
+    HTTPD_RUNNING=`netstat -natp | grep -E "(:80\s|:443\s).*LISTEN"`
+    if [ ! -z "$HTTPD_RUNNING" ];
+    then
+      echo "Could not shutdown the process, aborting the installation"
+      exit 1
+    fi
+  else
+    echo "No apachectl found, aborting the installation!"
+    echo "Please kill the following processes before attempting a new installation"
+    fuser -n tcp 80
+    fuser -n tcp 443
+    exit 1
+  fi
 fi
 
 #
@@ -53,41 +53,41 @@ fi
 PSQL_RUNNING=`netstat -natp | grep -E "(:5432\s).*LISTEN"`
 if [ ! -z "$PSQL_RUNNING" ];
 then
-	echo "There seems to be a server listening on port 5432"
-	echo "This might mean that there is a PostgreSQL server running on the machine already"
-	echo "Checking if the Postgres installation belongs to a previous CFEngine deployment"
-	PSQL_COMMAND=`ps -p `fuser -n tcp 5432 2>/dev/null` -o args=|cut -d' ' -f1`
-	if [ ! -z "$PSQL_COMMAND" ];
-	then
-		if [ "$PSQL_COMMAND" = "$PREFIX/bin/postgres" ];
-		then
-			echo "The PostgreSQL server belongs to a previous CFEngine deployment, shutting it down."
-			if [ -x "$PREFIX/bin/pg_ctl" ];
-			then
-				(cd /tmp && su cfpostgres -c "$PREFIX/bin/pg_ctl stop -D $PREFIX/state/pg/data -m smart")
-			else
-				echo "No pg_ctl found at $PREFIX/bin/pg_ctl, aborting"
-				exit 1
-			fi
-		else
-			echo "The PostgreSQL is not from a previous CFEngine deployment"
-			echo "This scenario is not supported, aborting installation"
-			ps -p `fuser -n tcp 5432 2>/dev/null` -o args=
-			exit 1
-		fi
-	else
-		echo "There is a process listening on the PostgreSQL port but it is not PostgreSQL, aborting."
-		echo -n "Command: "
-		ps -p `fuser -n tcp 5432 2>/dev/null` -o args=
-		echo "Please make sure that the process is not running before attempting the installation again."
-		exit 1
-	fi
-	PSQL_FINAL_CHECK=`netstat -natp | grep -E "(:5432\s).*LISTEN"`
-	if [ ! -z "$PSQL_FINAL_CHECK" ];
+  echo "There seems to be a server listening on port 5432"
+  echo "This might mean that there is a PostgreSQL server running on the machine already"
+  echo "Checking if the Postgres installation belongs to a previous CFEngine deployment"
+  PSQL_COMMAND=`ps -p `fuser -n tcp 5432 2>/dev/null` -o args=|cut -d' ' -f1`
+  if [ ! -z "$PSQL_COMMAND" ];
+  then
+    if [ "$PSQL_COMMAND" = "$PREFIX/bin/postgres" ];
     then
-	    echo "There is still a process listening on 5432, please kill it before retrying the installation. Aborting."
-		exit 1
-	fi
+      echo "The PostgreSQL server belongs to a previous CFEngine deployment, shutting it down."
+      if [ -x "$PREFIX/bin/pg_ctl" ];
+      then
+	(cd /tmp && su cfpostgres -c "$PREFIX/bin/pg_ctl stop -D $PREFIX/state/pg/data -m smart")
+      else
+	echo "No pg_ctl found at $PREFIX/bin/pg_ctl, aborting"
+	exit 1
+      fi
+    else
+      echo "The PostgreSQL is not from a previous CFEngine deployment"
+      echo "This scenario is not supported, aborting installation"
+      ps -p `fuser -n tcp 5432 2>/dev/null` -o args=
+      exit 1
+    fi
+  else
+    echo "There is a process listening on the PostgreSQL port but it is not PostgreSQL, aborting."
+    echo -n "Command: "
+    ps -p `fuser -n tcp 5432 2>/dev/null` -o args=
+    echo "Please make sure that the process is not running before attempting the installation again."
+    exit 1
+  fi
+  PSQL_FINAL_CHECK=`netstat -natp | grep -E "(:5432\s).*LISTEN"`
+  if [ ! -z "$PSQL_FINAL_CHECK" ];
+  then
+    echo "There is still a process listening on 5432, please kill it before retrying the installation. Aborting."
+    exit 1
+  fi
 fi
 #
 # We need a cfapache user for our web server
@@ -104,9 +104,25 @@ fi
 # Backup htdocs
 #
 if [ -d $PREFIX/httpd/htdocs ]; then
-    echo "A previous version of CFEngine Mission Portal was found,"
-    echo "creating a backup of it at /tmp/cfengine-htdocs.tar.gz"
-    tar zcf /tmp/cfengine-htdocs.tar.gz $PREFIX/httpd/htdocs
+  echo "A previous version of CFEngine Mission Portal was found,"
+  echo "creating a backup of it at /tmp/cfengine-htdocs.tar.gz"
+  tar zcf /tmp/cfengine-htdocs.tar.gz $PREFIX/httpd/htdocs
+fi
+
+#
+# Make a backup of the key CFE_CLIENT_SECRET_KEY, if any, and restore the
+# original file content.
+#
+if [ -f $PREFIX/share/GUI/application/config/appsettings.php ]; then
+  # Tricky quotes, because we need to both prevent expansion of $config,
+  # and keep the internal ' quotes.
+  fgrep '$config'"['MP_CLIENT_SECRET']" $PREFIX/httpd/htdocs/application/config/appsettings.php | sed -r -e 's/.*([a-z0-9]{32}).*/\1/i' > $PREFIX/CF_CLIENT_SECRET_KEY.tmp
+  UUID=$(tr -d '\n\r' < $PREFIX/CF_CLIENT_SECRET_KEY.tmp)
+  for path in share/GUI httpd/htdocs; do
+    sed -i s/"$UUID"/CFE_SESSION_KEY/ $PREFIX/$path/application/config/config.php
+    sed -i s/"$UUID"/CFE_CLIENT_SECRET_KEY/ $PREFIX/$path/application/config/appsettings.php
+  done
+  sed -i s/"$UUID"/CFE_CLIENT_SECRET_KEY/ $PREFIX/share/db/ootb_settings.sql
 fi
 
 exit 0
