clean-buildmachine: documented script
I also:
- fixed shellcheck issues
- added an if statement to prevent accedental deletion root on AIX in
  case of prefix being empty or undefined
- added a debug log message

Ticket: ENT-12600
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/clean-buildmachine b/build-scripts/clean-buildmachine
--- a/build-scripts/clean-buildmachine
+++ b/build-scripts/clean-buildmachine
@@ -1,10 +1,22 @@
 #!/bin/sh
 
-. `dirname "$0"`/functions
+# This script cleans a build machine by uninstalling cfbuild- prefixed packages
+# and by removing the contents of the PREFIX directory.
+#
+# Don't run this script on your dev machine!
+# You may accidentally delete something very important.
+
+. "$(dirname "$0")"/functions
 . detect-environment
 
 uninstall_cfbuild
 
+if [ -z "$PREFIX" ] || [ "$PREFIX" = "/" ]; then
+    echo "$(basename "$0"): Error: \$PREFIX is not defined, is empty, or is set to the root directory. Aborting to prevent accidental deletion."
+    exit 1
+fi
+
+echo "$(basename "$0"): Debug: Cleaning build host by deleting $PREFIX"
 case $OS in
     aix)
         sudo rm -rf "$PREFIX"/*
