compile: Fixed inconsistent indents
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/compile b/build-scripts/compile
--- a/build-scripts/compile
+++ b/build-scripts/compile
@@ -5,15 +5,15 @@
 . compile-options
 
 case "$PROJECT" in
-  community)
-    NOVA=no
-    ;;
-  nova)
-    NOVA=yes
-    ;;
-  *)
-    echo "$(basename "$0"): Error: Unknown project '$PROJECT'"
-    exit 42;;
+    community)
+        NOVA=no
+        ;;
+    nova)
+        NOVA=yes
+        ;;
+    *)
+        echo "$(basename "$0"): Error: Unknown project '$PROJECT'"
+        exit 42;;
 esac
 
 echo "$(basename "$0"): Debug: Running make in core repo..."
