detect-environment: Removed version substitution of code-names
Removed version substitution of the Debian release code-names (e.g.,
jessie, buster, etc.) from /etc/debian_version. Looking through the
[changelog](https://launchpad.net/debian/+source/base-files/+changelog)
for the base-files package in Debian, you can easily see that it has
never contained the code-names. At least not since version 5.0.3.
Furthermore, we have not updated the version substitution since Debian
10 which is End-of-Life.

Ticket: ENT-12600
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/detect-environment b/build-scripts/detect-environment
--- a/build-scripts/detect-environment
+++ b/build-scripts/detect-environment
@@ -197,24 +197,8 @@ detect_distribution()
     REL=$(cat /etc/debian_version)
     if ! echo "$REL" | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' > /dev/null
     then
-      case "$REL" in
-        wheezy*)
-          REL=7.0
-          ;;
-        jessie*)
-          REL=8.0
-          ;;
-        stretch*)
-          REL=9.0
-          ;;
-        buster*)
-          REL=10.0
-          ;;
-        *)
-          echo "Unable to detect version of Debian: $REL"
-          exit 42
-          ;;
-      esac
+      echo "Unable to detect version of Debian: $REL"
+      exit 42
     fi
 
     OS=debian
