detect-environment: Remove call to function fatal
The function "fatal" is not defined in this script. So it may not be
available.

Ticket: ENT-12600
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/detect-environment b/build-scripts/detect-environment
--- a/build-scripts/detect-environment
+++ b/build-scripts/detect-environment
@@ -341,7 +341,8 @@ detect_tools()
     then
         export MAKE
     else
-        fatal "GNU Make not found"
+        echo "Error: GNU Make not found"
+        exit 42
     fi
 
     export RPMBUILD_CMD=rpmbuild
