indent
(cherry picked from commit 2cf434d6d429a2baecd47bd5ce3390cca6bf5477)

diff --git a/build-scripts/functions b/build-scripts/functions
--- a/build-scripts/functions
+++ b/build-scripts/functions
@@ -385,8 +385,8 @@ mount_procfs()
 #     fatal "exiting with default error code"
 fatal()
 {
-  echo "FATAL ERROR: $1" >&2
-  exit ${2-1}
+    echo "FATAL ERROR: $1" >&2
+    exit ${2-1}
 }
 
 # Check that command exists, and print its full path,
