functions: fixed shellcheck issues
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/functions b/build-scripts/functions
--- a/build-scripts/functions
+++ b/build-scripts/functions
@@ -22,6 +22,7 @@ try_exec() {
 
 broken_posix_shell() {
     unset foo
+    # shellcheck disable=SC3043
     local foo=1
     test "$foo" != "1"
 }
@@ -137,34 +138,34 @@ grep_q() {
 #
 
 uninstall_rpms() {
-    PKGS=$(rpm -qa --queryformat "%{Name}-%{Version}\n" | grep '^'$1 || true)
+    PKGS=$(rpm -qa --queryformat "%{Name}-%{Version}\n" | grep "^$1" || true)
     if [ -n "$PKGS" ]; then
-        retry_wrapper sudo rpm -e $PKGS
+        retry_wrapper sudo rpm -e "$PKGS"
     fi
 }
 uninstall_debs() {
-    PKGS=$(dpkg -l | tail -n+6 | awk '{print $2}' | grep '^'$1 || true)
+    PKGS=$(dpkg -l | tail -n+6 | awk '{print $2}' | grep "^$1" || true)
     if [ -n "$PKGS" ]; then
-        retry_wrapper sudo dpkg --purge $PKGS
+        retry_wrapper sudo dpkg --purge "$PKGS"
     fi
 }
 uninstall_solaris_pkgs() {
-    PKGS=$(pkginfo | awk '{print $2}' | grep '^'$1'$' || true)
+    PKGS=$(pkginfo | awk '{print $2}' | grep "^$1$" || true)
     if [ -n "$PKGS" ]; then
-        retry_wrapper sudo /usr/sbin/pkgrm -n $PKGS
+        retry_wrapper sudo /usr/sbin/pkgrm -n "$PKGS"
     fi
 }
 uninstall_hpux_pkgs() {
-    PKGS=$(swlist | awk '{print $1}' | grep '^'$1'$' || true)
+    PKGS=$(swlist | awk '{print $1}' | grep "^$1$" || true)
 
     for p in $PKGS; do
-        sudo /usr/sbin/swremove $p
+        sudo /usr/sbin/swremove "$p"
     done
 }
 uninstall_freebsd_pkgs() {
-    PKGS=$(pkg_info | awk '{print $1}' | grep '^'$1 || true)
+    PKGS=$(pkg_info | awk '{print $1}' | grep "^$1" || true)
     if [ -n "$PKGS" ]; then
-        retry_wrapper sudo pkg_delete $PKGS
+        retry_wrapper sudo pkg_delete "$PKGS"
     fi
 }
 
@@ -197,7 +198,7 @@ uninstall_cfbuild_devel() {
 query_pkg() {
     case "$DEP_PACKAGING" in
     rpm) rpm -qa --provides | grep_q "^$1 " ;;
-    deb) dpkg -s $1 2>&1 | grep_q '^Status: .*ok installed' ;;
+    deb) dpkg -s "$1" 2>&1 | grep_q '^Status: .*ok installed' ;;
     *)
         echo "ERROR query_pkg not implemented for $DEP_PACKAGING"
         exit 1
@@ -267,7 +268,7 @@ remote_script_general() {
     ENVVARS="$ENVVARS TEST_MACHINE=$TEST_MACHINE"
     ENVVARS="$ENVVARS TEST_SHELL=$TEST_SHELL"
 
-    (eval $LOGIN_COMMAND env $ENVVARS "$SCRIPT_BASEDIR"/buildscripts/build-scripts/"$SCRIPT")
+    (eval "$LOGIN_COMMAND" env "$ENVVARS" "$SCRIPT_BASEDIR"/buildscripts/build-scripts/"$SCRIPT")
 }
 
 remote_script() {
@@ -276,10 +277,10 @@ remote_script() {
 }
 
 projects_to_test() {
-    if test "x$PROJECT" = "xcommunity"; then
+    if test "$PROJECT" = "community"; then
         echo "core masterfiles"
     else
-        if test "x$ROLE" = "xhub"; then
+        if test "$ROLE" = "hub"; then
             echo "core enterprise nova masterfiles"
         else
             echo "core enterprise masterfiles"
@@ -390,17 +391,17 @@ mount_procfs() {
 #     fatal "exiting with default error code"
 fatal() {
     echo "$(basename "$0"): FATAL ERROR: $1" >&2
-    exit ${2-1}
+    exit "${2-1}"
 }
 
 log_info() {
-    echo "INFO: $@" 1>&2
+    echo "INFO:" "$@" 1>&2
 }
 
 # Append a space and string $2 to variable $1, for example:
 # func_append V "blah" is equivalent to  V="$V blah".
 var_append() {
-    eval $1=\$$1\\ \$2
+    eval "$1=\$$1"\\ \$2
 }
 
 # Return True if string $2 exists in variable $1.
@@ -450,27 +451,34 @@ func_whereis() {
 # Only works as mktemp -d /path/to/tmpdir.XXXX
 func_mktemp() {
     # Only works as mktemp -d
-    [ x$1 != x-d ] && fatal "func_mktemp: error, first argument must be -d"
-    [ x$2 = x ] && fatal "func_mktemp: requires two arguments"
+    [ "$1" != -d ] && fatal "func_mktemp: error, first argument must be -d"
+    [ "$2" = "" ] && fatal "func_mktemp: requires two arguments"
 
     # $RANDOM does not exist on Solaris 9 /bin/sh, use $$ as fallback
-    my_tmpdir=$(echo $2 | sed 's/XX*/'${RANDOM-$$}/)
+
+    # shellcheck disable=SC3028
+    # > In POSIX sh, RANDOM is undefined.
+    # That's why we fallback to $$.
+
+    my_tmpdir=$(echo "$2" | sed 's/XX*/'${RANDOM-$$}/)
 
     save_mktemp_umask=$(umask)
     umask 0077
     # Set -e will cause this to fail if it already exists
     mkdir "$my_tmpdir"
-    umask $save_mktemp_umask
+    umask "$save_mktemp_umask"
 
-    [ -d "$my_tmpdir" ] &&
-        echo "$my_tmpdir" ||
+    if [ -d "$my_tmpdir" ]; then
+        echo "$my_tmpdir"
+    else
         fatal "func_mktemp: failed creating temporary directory $my_tmpdir"
+    fi
 }
 
 # mktempdir TEMPLATE
 # Example: mktempdir /tmp/dir.XXXXXX
 mktempdir() {
-    [ x$1 = x ] && fatal "mktempdir: TEMPLATE directory argument missing"
+    [ "$1" = "" ] && fatal "mktempdir: TEMPLATE directory argument missing"
 
     # HP-UX has its own non-POSIX mktemp, so override it.
     # If not on HP-UX, search PATH for the 'mktemp' or 'gmktemp' command.
@@ -480,7 +488,7 @@ mktempdir() {
         my_mktemp=$(func_which mktemp gmktemp) ||
         my_mktemp=func_mktemp
 
-    $my_mktemp -d $1
+    $my_mktemp -d "$1"
 }
 
 # Print the sha256sum of $1 or stdin.
@@ -502,7 +510,7 @@ func_decompress() {
     *.gz | *.tgz) gzip -dc "$@" ;;
     *.bz2) bzip2 -dc "$@" ;;
 
-    *) fatal "Unknown compression for file: $@" ;;
+    *) fatal "Unknown compression for file:" "$@" ;;
     esac
 }
 
@@ -510,7 +518,7 @@ func_decompress() {
 #                retrying in case of failure.
 # WARNING: do not pipe the output as stdout is altered!
 retry_wrapper() {
-    operation="$@"
+    operation="$*"
     [ "$operation" = "" ] && fatal "retry_wrapper: no arguments"
 
     # SLEEP: which sleep program to use
@@ -520,7 +528,7 @@ retry_wrapper() {
     maxtries=5
     pause=30
 
-    while [ $maxtries != 0 ]; do
+    while [ "$maxtries" != 0 ]; do
         echo "* retry_wrapper:  $operation"
 
         if $operation; then
@@ -529,8 +537,9 @@ retry_wrapper() {
         else
             err_ret=$?
             # in case say dpkg locks are held by automatic updates or something
+            # shellcheck disable=SC2009
             ps -efl | grep -P '(apt|dpkg|yum|dnf|zypper|rpm|pkg)'
-            maxtries=$(expr $maxtries - 1)
+            maxtries=$((maxtries - 1))
             echo "* FAILURE $err_ret"
             echo "* Sleeping for:  $pause seconds"
             echo "* Retries left:  $maxtries"
@@ -538,7 +547,7 @@ retry_wrapper() {
         fi
     done
 
-    return $err_ret
+    return "$err_ret"
 }
 
 rm_if_empty() {
@@ -551,6 +560,7 @@ rm_if_empty() {
 # Use this function on verbose commands to silence the output unless it returns
 # a non-zero exit code
 run_and_print_on_failure() {
+    # shellcheck disable=SC3043
     local temp_output_file
     if command -v mktemp >/dev/null; then
         temp_output_file=$(mktemp)
@@ -568,6 +578,7 @@ run_and_print_on_failure() {
         touch "$temp_output_file"
     fi
 
+    # shellcheck disable=SC3043
     local exit_code=0
     if "$@" >"$temp_output_file" 2>&1; then
         : # NOOP
