Use fatal() as defined in functions script.
(cherry picked from commit 0d0a29b6b4e55b9a5e19aa79f5d20e215c8af59a)

diff --git a/build-scripts/functions b/build-scripts/functions
--- a/build-scripts/functions
+++ b/build-scripts/functions
@@ -364,7 +364,7 @@ mount_procfs()
 #     fatal "exiting with default error code"
 fatal()
 {
-  echo "$1" >&2
+  echo "FATAL ERROR: $1" >&2
   exit ${2-1}
 }
 
