functions: Added basename of executing script to the fatal error function
Having the basename printed along side the error message will aid in
debugging by giving you a clue as to where the fatal error happened.

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/functions b/build-scripts/functions
--- a/build-scripts/functions
+++ b/build-scripts/functions
@@ -415,7 +415,7 @@ mount_procfs()
 #     fatal "exiting with default error code"
 fatal()
 {
-    echo "FATAL ERROR: $1" >&2
+    echo "$(basename "$0"): FATAL ERROR: $1" >&2
     exit ${2-1}
 }
 
