test-on-testmachine: use logging functions where applicable
Logging functions prefixes the running scripts filename to the log
message which aids in debugging.

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/test-on-testmachine b/build-scripts/test-on-testmachine
--- a/build-scripts/test-on-testmachine
+++ b/build-scripts/test-on-testmachine
@@ -17,7 +17,7 @@ chroot)
     ;;
 *)
     # Add VMs, etc here.
-    echo "Only chroot test machines are supported at the moment."
+    log_error "Only chroot test machines are supported at the moment."
     exit 1
     ;;
 esac
@@ -65,12 +65,12 @@ chroot)
             # This next part is very confusing when mixed with "set -x".
             # Turn it off inside the subshell while printing this.
             set +x
-            echo "Error: Found processes left behind in the chroot. I'm killing them, but the build will fail, so clean up your mess!"
+            log_error "Found processes left behind in the chroot. I'm killing them, but the build will fail, so clean up your mess!"
             echo "Found PID $pid. Info from 'ps -ef'"
-            echo "--------------"
+            echo "--------------" 1>&2
             # shellcheck disable=SC2009
-            ps -ef | grep "$pid" | grep -v grep
-            echo "--------------"
+            ps -ef | grep "$pid" | grep -v grep 1>&2
+            echo "--------------" 1>&2
         )
     done
 
@@ -100,6 +100,6 @@ if [ "$PROJECT" = nova ]; then
 fi
 
 if [ $return_code -ne 0 ]; then
-    echo "ERROR: we just finished cleaning up, but earlier command had returned: $return_code"
+    log_error "We just finished cleaning up, but earlier command had returned: $return_code"
     exit $return_code
 fi
