transfer-to-testmachine: added log messages to aid debugging
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

diff --git a/build-scripts/transfer-to-testmachine b/build-scripts/transfer-to-testmachine
--- a/build-scripts/transfer-to-testmachine
+++ b/build-scripts/transfer-to-testmachine
@@ -27,10 +27,11 @@ chroot)
     # Don't lose the trailing slash!
     TESTMACHINE_URI=$HOME/testmachine-chroot/
     EXCLUDES="--exclude testmachine-chroot --exclude .git"
+    log_debug "Using chroot test machine at: $TESTMACHINE_URI"
     ;;
 *)
     # Add VMs, etc here.
-    echo "Only chroot test machines are supported at the moment."
+    log_error "Unsupported test machine type: $TEST_MACHINE. Only chroot test machines are supported at the moment."
     exit 1
     ;;
 esac
@@ -44,12 +45,15 @@ esac
 # middle of BASEDIR like "/home/jenkins/.jenkinsdir/etc"
 # (Google Cloud Jenkins plugin likes to create them)
 BASEDIR_NO_DOT="$(echo "$BASEDIR" | sed -e 's,/\./,/,g;s,/\.$,,')"
+
+log_debug "Starting keepalive process for long transfer"
 touch .keepalive-echo
 (while test -e .keepalive-echo; do
     sleep 60
     echo Keep alive
 done) &
 
+log_debug "Transferring BASEDIR contents: $BASEDIR_NO_DOT/ -> $TESTMACHINE_URI"
 # shellcheck disable=SC2086
 # > Double quote to prevent globbing and word splitting.
 # We want word splitting here
@@ -57,8 +61,20 @@ done) &
 # shellcheck disable=SC2024
 # > sudo doesn't affect redirects. Use ..| sudo tee file
 # We don't care
-sudo rsync -avR $EXCLUDES --delete --delete-excluded "$BASEDIR_NO_DOT/" $TESTMACHINE_URI >/tmp/rsync.log
+if ! sudo rsync -avR $EXCLUDES --delete --delete-excluded "$BASEDIR_NO_DOT/" $TESTMACHINE_URI >/tmp/rsync.log; then
+    log_error "Failed to transfer BASEDIR contents"
+    rm .keepalive-echo
+    exit 1
+fi
+
+log_debug "Transferring PREFIX contents: $PREFIX/ -> $TESTMACHINE_URI"
 # shellcheck disable=SC2086
 # shellcheck disable=SC2024
-sudo rsync -avR $EXCLUDES --delete --delete-excluded "$PREFIX/" $TESTMACHINE_URI >>/tmp/rsync.log
+if ! sudo rsync -avR $EXCLUDES --delete --delete-excluded "$PREFIX/" $TESTMACHINE_URI >>/tmp/rsync.log; then
+    log_error "Failed to transfer PREFIX contents"
+    rm .keepalive-echo
+    exit 1
+fi
+
 rm .keepalive-echo
+log_debug "Transfer to test machine completed successfully"
