install proper pgtap
also, retab the file

diff --git a/build-scripts/travis b/build-scripts/travis
--- a/build-scripts/travis
+++ b/build-scripts/travis
@@ -135,7 +135,7 @@ case "$JOB" in
             ./07_packages/00*.cf \
             ./10_files/11_xml_edits \
             ./25_cf-execd
-	set +e
+        set +e
         sudo ./testall \
             --agent=/var/cfengine/bin/cf-agent \
             --cfpromises=/var/cfengine/bin/cf-promises \
@@ -147,10 +147,10 @@ case "$JOB" in
             --rpmvercmp=$HOME/rpmvercmp \
             --tests=common,timed,slow,errorexit,serial,network,libxml2,libcurl,unsafe \
             --gainroot=sudo
-	RET1=$?
-	set -e
-	pwd
-	ls -lad workdir
+        RET1=$?
+        set -e
+        pwd
+        ls -lad workdir
         sudo tar cz * >core-tests-acceptance.tar.gz
         s3cmd put --reduced-redundancy --no-progress \
             core-tests-acceptance.tar.gz $S3_DIR/core-tests-acceptance.tar.gz
@@ -163,7 +163,7 @@ case "$JOB" in
         echo export CORE=../../../core > testall.env
         echo export ENTERPRISE=../.. >> testall.env
         echo export CFENGINE_TEST_OVERRIDE_EXTENSION_LIBRARY_DIR=/var/cfengine/lib >> testall.env
-	set +e
+        set +e
         sudo ./testall \
             --agent=/var/cfengine/bin/cf-agent \
             --cfpromises=/var/cfengine/bin/cf-promises \
@@ -175,16 +175,15 @@ case "$JOB" in
             --rpmvercmp=$HOME/rpmvercmp \
             --tests=common,timed,slow,errorexit,serial,network,libxml2,libcurl,unsafe \
             --gainroot=sudo
-	RET2=$?
-	set -e
+        RET2=$?
+        set -e
         sudo tar cz * >enterprise-tests-acceptance.tar.gz
         s3cmd put --reduced-redundancy --no-progress \
             enterprise-tests-acceptance.tar.gz $S3_DIR/enterprise-tests-acceptance.tar.gz
-	exit `expr $RET1 + $RET2` # if one of them is non-zero, fail the build
+        exit `expr $RET1 + $RET2` # if one of them is non-zero, fail the build
         ;;
 
     ( reporting-test )
-        sudo apt-get install pgtap
         s3cmd get $DEB_PACKAGE cfe.deb
         sudo dpkg -i cfe.deb
         sudo service cfengine3 restart
@@ -195,6 +194,9 @@ case "$JOB" in
         sudo chmod a+x /var/cfengine/bin/cf-testd
         sudo chown root:root nova/tests/reporting/minimal.cf
         sudo chmod 600 nova/tests/reporting/minimal.cf
+        wget https://ftp.postgresql.org/pub/repos/apt/pool/main/p/pgtap/postgresql-10-pgtap_0.97.0-3.pgdg90%2b1_all.deb
+        sudo dpkg -i postgresql-10-pgtap_0.97.0-3.pgdg90+1_all.deb
+        sudo cp /usr/share/postgresql/10/extension/pgtap* /var/cfengine/share/postgresql/extension/
         cd nova/tests/reporting
         sudo bash temporary_test_runner.sh --no-files-setup --no-db-setup
     ;;
